FROM sourcepole/qwc-uwsgi-base:alpine-v2023.05.12

ADD . /srv/qwc_service

# git: Required for pip with git repos
# postgresql-dev g++ python3-dev: Required for psycopg2-binary
RUN \
    apk add --no-cache --virtual runtime-deps postgresql-libs && \
    apk add --no-cache --virtual build-deps --update git postgresql-dev g++ python3-dev && \
    pip3 install --no-cache-dir -r /srv/qwc_service/requirements.txt && \
    apk del build-deps

# download JSON schemas for QWC services
ENV JSON_SCHEMAS_PATH=/srv/qwc_service/schemas/
RUN python3 /srv/qwc_service/download_json_schemas.py
